ogl_spell:
  name: Friends
  level: 0
  components: "-"
  duration: 1 Minute, concentration
  range: -1
  casting_time: 1 Action
  description: >
    For the duration, you have advantage on all Charisma checks directed at one creature of your choice
    that isn’t hostile toward you. When the spell ends, the creature realizes that you used magic to
    influence its mood and becomes hostile toward you. A creature prone to violence might attack you.
    Another creature might seek retribution in other ways (at the DM’s discretion), depending on the
    nature of your interaction with it.
