dndpkmn_attack:
  name: Razor Leaf
  type: Grass
  description: All creatures within a 20 foot fan must make a Dexterity saving throw. If failed, deal 2D6 slashing damage, if successful deal half damage. Your DC save for this attack is 9+2(STAB)+2(PR)+3(DEX) modifier.
  atk_bonus_or_save:
    dice: ''
    fixed: 9
    stats: ["dex"]
  pp: 1
  target: Creatures
  range: 20
